export const iconNames = {
  CLOSE_X: 'close-x',
  ARROW_RIGHT: 'arrow-right',
  ARROW_LEFT: 'arrow-left',
  ARROW_DOWN: 'arrow-down',
  ARROW_UP: 'arrow-up',
  EMAIL: 'email',
  SEARCH: 'search',
  HAMBURGER_MENU: 'hamburger',
  TICK: 'tick',
  CIRCLE: 'circle',
  CIRCLE_TICKED: 'circle-tick',
  CIRCLE_X: 'circle-x',
  CIRCLE_ALERT: 'circle-attention',
  CIRCLE_CHECKBOX_TICKED: 'circle-checkbox-ticked',
  CIRCLE_CHECKBOX_UNTICKED: 'circle-checkbox-unticked',
};
